title: "The PROSE Consortium"
description: The Open Source Ecosystem for STEM Education, supported by NSF
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false
